---

name: Test changes

on:
  pull_request:
  push:
    branches:
      - 1.3.x
  workflow_dispatch:
    inputs:
      ref:
        description: A git reference to check out.
        default: 1.3.x
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7  # 2023-06-07
          - 3.8  # 2024-10
          - 3.9  # 2025-10
          - "3.10"  # 2026-10
          - 3.11  # 2027-10
          - pypy3.7
          - pypy3.8
          - pypy3.9
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install tox
      - run: tox -e py

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      - run: pip install --upgrade build pip
      - run: python -m build --wheel
      - run: pip install dist/*.whl

  other:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: doctest
          - environment: linting
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install tox
      - run: tox -e ${{ matrix.environment }}

...
